### ISSUE TITLE
Bricked my system

### ISSUE THREAD

**Issue by ghost** [denko-rb/denko#1]
I installed this on Linux, but then it somehow messed up my bash so bad, I can't do anything anymore at all.
I have no way of troubleshooting this, as my system is bricked.

**Comment by vickash** [comment]
Can you give some more information?

Are you using the master branch? Or did you install with `gem install denko`?
What Ruby version?
Preinstalled system Ruby, rbenv or rvm?

The only thing this gem adds to your PATH is a "loader" script (provided by RubyGems itself, or a Ruby version manager), which dynamically loads and runs the script `bin/denko` from this repo. If you aren't trying to run it, it should have no effect on your bash session.

**Comment by ghost** [comment]
So, I found the issue :)
Error code: ID-10-T
I use Arch Linux  (Considered to be the most unstable distro )
I use a franken-PC, made of random spare parts.
Something, very, very specific can easily happen to brick my specific system, it's not the application's fault.
